### ISSUE TITLE
[BUG] Direct install from repository gives Atari errors on import

### ISSUE THREAD

**Issue by jbuckman** [sail-sg/envpool#225]
## To Reproduce

Installed via

```bash
python -m pip install 'envpool @ git+https://github.com/sail-sg/envpool'
```

It seems to work, but importing gives

```python
>>> import envpool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jbuckman/.local/lib/python3.9/site-packages/envpool/__init__.py", line 16, in <module>
    import envpool.entry  # noqa: F401
  File "/home/jbuckman/.local/lib/python3.9/site-packages/envpool/entry.py", line 16, in <module>
    import envpool.atari.registration  # noqa: F401
  File "/home/jbuckman/.local/lib/python3.9/site-packages/envpool/atari/__init__.py", line 19, in <module>
    from .atari_envpool import _AtariEnvPool, _AtariEnvSpec
ModuleNotFoundError: No module named 'envpool.atari.atari_envpool'```

## System info

```python
>>> import numpy, sys
>>> print(numpy.__version__, sys.version, sys.platform)
1.23.0 3.9.6 (default, Jul 12 2021, 18:23:59) 
[GCC 9.3.0] linux
```

## Checklist

- [ x] I have checked that there is no similar issue in the repo (**required**)
- [ x] I have read the [documentation](https://envpool.readthedocs.io/) (**required**)
- [ x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Trinkle23897** [comment]
You cannot use this method to install, instead, use bazel via `make bazel-release`. Otherwise the binary won’t be compiled.
