### ISSUE TITLE
metaclass conflict

### ISSUE THREAD

**Issue by NJW4812** [sail-sg/envpool#288]
When I run train.py(tags v5.0) in pycharm, I find this error
Traceback (most recent call last):
  File "E:\Chrome download\yolov5-5.0\yolov5-5.0\train.py", line 21, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\tensorboard\__init__.py", line 13, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\tensorboard\writer.py", line 13, in <module>
    from tensorboard.summary.writer.event_file_writer import EventFileWriter
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\summary\__init__.py", line 22, in <module>
    from tensorboard.summary import v1  # noqa: F401
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\summary\v1.py", line 23, in <module>
    from tensorboard.plugins.histogram import summary as _histogram_summary
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\plugins\histogram\summary.py", line 35, in <module>
    from tensorboard.plugins.histogram import summary_v2
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\plugins\histogram\summary_v2.py", line 35, in <module>
    from tensorboard.util import tensor_util
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\util\tensor_util.py", line 20, in <module>
    from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\compat\tensorflow_stub\__init__.py", line 25, in <module>
    from . import app  # noqa
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\compat\tensorflow_stub\app.py", line 21, in <module>
    from . import flags
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\compat\tensorflow_stub\flags.py", line 25, in <module>
    from absl.flags import *  # pylint: disable=wildcard-import
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\absl\flags\__init__.py", line 35, in <module>
    from absl.flags import _argument_parser
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\absl\flags\_argument_parser.py", line 82, in <module>
    class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Can you help me to resolve it?

**Comment by Trinkle23897** [comment]
This is not an envpool-related issue. The traceback suggests it’s a PyTorch tensorboard issue.
The suggestion I can give is to either upgrade tensorboard and PyTorch to the newest possible version, or open an issue in their GitHub repo.
