### ISSUE TITLE
[BUG] Error running mujoco-gym tasks with the parameter xml_file

### ISSUE THREAD

**Issue by dynamicDr** [sail-sg/envpool#295]
An error occur using envpool to run mujoco-gym tasks with the parameter xml_file (I referred to https://www.gymlibrary.dev/environments/mujoco/ant/ for this parameter).

The following code runs successfully:
```python
env = envpool.make("Ant-v4", env_type="gym", num_envs=100, healthy_reward=1)
```
However, when I run the following code (with the parameter xml_file):
```python
env = envpool.make("Ant-v4", env_type="gym", num_envs=100, xml_file="ant.xml")
```
I encounter the following error:
Traceback (most recent call last):
File "/tianshou/mytest/envpool_test_2.py", line 11, in <module>
env = envpool.make("Ant-v4", env_type="gym", num_envs=100, xml_file="ant.xml")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/tianshou/lib/python3.11/site-packages/envpool/registration.py", line 65, in make
spec = self.make_spec(task_id, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/tianshou/lib/python3.11/site-packages/envpool/registration.py", line 99, in make_spec
config = spec_cls.gen_config(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Config.new() got an unexpected keyword argument 'xml_file'

**Comment by Trinkle23897** [comment]
Sorry this is hardcode here: https://github.com/sail-sg/envpool/blob/f411fc26c8999ba5b9c39974344903b164486d1a/envpool/mujoco/gym/ant.h#L89

**Comment by anthony0727** [comment]
can't we use custom xml file?
